### ISSUE TITLE
Makefile only supports debian based distros

### ISSUE THREAD

**Issue by halvko** [SSoelvsten/Interaction_Design_in_a_Nutshell#40]
The first command in the makefile is a call to apt, which the user cannot be expected to have installed

**Comment by SSoelvsten** [comment]
Since that part of the makefile is somewhat redundant (couid also just require users to resolve dependencies), and the amount of time required to properly make a `tlmgr` dependency script is not something I can afford, I would classify this somewhat as a 'Won't Fix' and instead just remove the confusion.
